### ISSUE TITLE
Styling Changes

### ISSUE THREAD

**Issue by dougthor42** [rgalanakis/hostthedocs#15]
Discussion area for the comments in https://github.com/rgalanakis/hostthedocs/pull/14#issuecomment-304392399.

@rgalanakis

**Comment by rgalanakis** [comment]
IIRC this is using bootstrap, is there a class you can assign to the select element to look better?

**Comment by dougthor42** [comment]
## Without Bootstrap
Perhaps something from [here](https://codepen.io/ericrasch/pen/zjDBx)?

I'm partial to this one:
![image](https://cloud.githubusercontent.com/assets/5386897/26514592/97806382-4227-11e7-8c1f-9f57ebb94931.png)

## With Bootstrap

How about something like this?
![image](https://cloud.githubusercontent.com/assets/5386897/26514909/33453ba6-422a-11e7-9eca-cb5a4ce8f399.png)

**Comment by dougthor42** [comment]
@rgalanakis Any thoughts on the Bootstrap style I chose?
