### ISSUE TITLE
can't upload doc

### ISSUE THREAD

**Issue by alenweiru** [rgalanakis/hostthedocs#27]

**Comment by alenweiru** [comment]
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:5000
DEBUG:urllib3.connectionpool:http://127.0.0.1:5000 "POST /hmfd HTTP/1.1" 500 291

**Comment by rgalanakis** [comment]
What OS and version of Python?

**Comment by alenweiru** [comment]
python3.7.1

**Comment by rgalanakis** [comment]
This should be fixed by #29; please reopen/comment/open a new issue if not.
