### ISSUE TITLE
Multiple rows of display items don't always "flow" correctly

### ISSUE THREAD

**Issue by Aaron-Hartwig** [rgalanakis/hostthedocs#32]
A HTD I work with has enough items to flow into two rows. However the sizes do not all perfectly align so the way Bootstrap flows everything is a little strange. 

![image](https://user-images.githubusercontent.com/5115774/79265646-0a1d3a00-7e5c-11ea-9bb1-1d20b2a569d8.png)

**Comment by nathanaelhuffman** [comment]
I think this can be fixed by adding a <div class="clearfix"></div> after every 4th column.  Would you entertain a pull request for this?

**Comment by rgalanakis** [comment]
Yeah if anyone wants to put up a PR with a fix I'm happy to merge it.

**Comment by rgalanakis** [comment]
FWIW I think this is probably a clearfix issue- the 3rd item is causing some issues. Bootstrap 4 handles this much better. You may want to get rid of the grid for this and use flexbox directly.
