### ISSUE TITLE
Cross project search

### ISSUE THREAD

**Issue by shilpa-0** [rgalanakis/hostthedocs#41]
Hi, 

We use a fork of hostthedocs in our organization.

Could you please provide some hints on how a cross-project search feature could be implemented? 

Or do you have plans of implementing this feature? 

Thanks

**Comment by rgalanakis** [comment]
Hi @shilpa-0, I don't have any plans for this feature, as cross-project search is a pretty different concern than the normal Sphinx search. For example see this thread: https://groups.google.com/g/sphinx-users/c/cf574LSBH0g/m/nL85DFikAgAJ

I would suggest looking at Algolia (I can recommend their service as a former customer). I suspect folks have already built plugins to integrate it and Sphinx/python do indexing. Here is one such attempt, I'm sure there are others: https://github.com/readthedocs/sphinx_rtd_theme/issues/761 But it will still be some work to integrate.

It would be possible to integrate cross-project search into HTD itself, and generate the cross-project index at upload time, and serve it from the same Python process. I don't think there are good Python search engines; you could write a Go library using Bleve, or a similar language/library, and call it from the server.

No simple solution I'm afraid. I do consulting through my company [Lithic Technology](https://lithic.tech), if you want a solution for your organization.
